---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-fasthttp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-fasthttp
  template:
    metadata:
      labels:
        app: hello-fasthttp
    spec:
      enableServiceLinks: false
      imagePullSecrets:
        - name: regcred
      containers:
        - name: hello-fasthttp
          image: hello-fasthttp
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 8080
              name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: hello-fasthttp
  labels:
    app: hello-fasthttp
spec:
  selector:
    app: hello-fasthttp
  ports:
  - protocol: TCP
    port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-fasthttp
  annotations:
    kubernetes.io/ingress.class: shared
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    external-dns.alpha.kubernetes.io/target: traefik.codemowers.ee
spec:
  rules:
  - host: hello-lauri.codemowers.ee
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: hello-fasthttp
            port:
              number: 8080
  tls:
  - hosts:
    - "*.codemowers.ee"
